### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TAP1994** [the872/parser330#1]
So this may just be a problem with me, but I'm not super familiar with python. I can see the the attributes and the accessors to your parser.py file, but something like:
```
{authors}
URL: <{url}>
'''.format(
        project=metadata.project,
        version=metadata.version,
        authors='\n'.join(author_strings),
        url=metadata.url)

    arg_parser = argparse.ArgumentParser(
        prog=argv[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=metadata.description,
        epilog=epilog)
    arg_parser.add_argument(
        '-V', '--version',
        action='version',
        version='{0} {1}'.format(metadata.project, metadata.version))

    arg_parser.parse_args(args=argv[1:])

    print(epilog)

    return 0
```
I just don't have a clue what it does. I probably need some catching up in python, but I think you should add some documentation detailing what some of the functions do.

**Comment by the872** [comment]
As I referenced in the README, I did use a [python template](https://github.com/seanfisk/python-project-template) which sets up and organizes projects in a certain way. The [main.py](https://github.com/seanfisk/python-project-template/blob/master/my_module/main.py.tpl) is pretty standard and simply ties the project together. I suppose I can go back and comment it out to show what does what. However, the main code that I worked on can be found in my [parser](https://github.com/the872/parser330/blob/master/parser330/parser.py) and [tests](https://github.com/the872/parser330/blob/master/tests/test_parser.py).

**Comment by jthompson18** [comment]
@TAP1994 that main doesn't do anything its a generic thing that is set up by the project generation that is just there for the project to build and for the tests to for the set up to run.

**Comment by the872** [comment]
I agree with @jthompson18 and frankly I'm going back on my original idea to comment the auto generated code because I don't think there is much value to do so. @TAP1994, if you have any questions regarding the two files that are specific to this project, feel free to open a new request with your specific question.
