### ISSUE TITLE
Code Understanding

### ISSUE THREAD

**Issue by ConnorMacDonell** [the872/parser330#2]
Good reuse of existing code for your own purposes. One suggestion I would make is that you know how and why everything functions as it does. I'm not saying that you do not, but make certain that you do. Since the code you are using is quite complex, many people will have trouble reading and working with it, therefore it is very important that you have a thorough understanding of the code so that you can explain it to teammates and bosses alike.

**Comment by the872** [comment]
As I referenced in the [README](https://github.com/the872/parser330/blob/master/README.rst), I did use a [python template](https://github.com/seanfisk/python-project-template) which sets up and organizes projects in a certain way. That would probably account for a ton of the complexity that you are seeing. However, the main code that I worked on can be found in my [parser](https://github.com/the872/parser330/blob/master/parser330/parser.py) and [tests](https://github.com/the872/parser330/blob/master/tests/test_parser.py). 

Feel free to open a new request and ask a more specific question if you come across something that looks unfamiliar. I'll look into going back to add more comments for the template files that were automatically set up.
